ChannelSettings:
  description: Base channel settings. Only the channel settings corresponding to the channel specified in the channelType field is or should be present.
  discriminator: channelType
  required:
    - channelType
    - direction
  properties:
    channelType:
      description: Channel type code
      type: string
    direction:
      description: 0 for Rx only, 1 for Tx only or 2 for any number and direction (default 0)
      type: integer
    originatorDeviceSetIndex:
      description: Optional for reverse API. This is the device set index from where the message comes from.
      type: integer
    originatorChannelIndex:
      description: Optional for reverse API. This is the channel index from where the message comes from.
      type: integer
    ADSBDemodSettings:
      $ref: "/doc/swagger/include/ADSBDemod.yaml#/ADSBDemodSettings"
    AISDemodSettings:
      $ref: "/doc/swagger/include/AISDemod.yaml#/AISDemodSettings"
    AISModSettings:
      $ref: "/doc/swagger/include/AISMod.yaml#/AISModSettings"
    AMDemodSettings:
      $ref: "/doc/swagger/include/AMDemod.yaml#/AMDemodSettings"
    AMModSettings:
      $ref: "/doc/swagger/include/AMMod.yaml#/AMModSettings"
    APTDemodSettings:
      $ref: "/doc/swagger/include/APTDemod.yaml#/APTDemodSettings"
    ATVDemodSettings:
      $ref: "/doc/swagger/include/ATVDemod.yaml#/ATVDemodSettings"
    ATVModSettings:
      $ref: "/doc/swagger/include/ATVMod.yaml#/ATVModSettings"
    BeamSteeringCWModSettings:
      $ref: "/doc/swagger/include/BeamSteeringCWMod.yaml#/BeamSteeringCWModSettings"
    BFMDemodSettings:
      $ref: "/doc/swagger/include/BFMDemod.yaml#/BFMDemodSettings"
    ChannelAnalyzerSettings:
      $ref: "/doc/swagger/include/ChannelAnalyzer.yaml#/ChannelAnalyzerSettings"
    ChirpChatDemodSettings:
      $ref: "/doc/swagger/include/ChirpChatDemod.yaml#/ChirpChatDemodSettings"
    ChirpChatModSettings:
      $ref: "/doc/swagger/include/ChirpChatMod.yaml#/ChirpChatModSettings"
    DATVModSettings:
      $ref: "/doc/swagger/include/DATVMod.yaml#/DATVModSettings"
    DATVDemodSettings:
      $ref: "/doc/swagger/include/DATVDemod.yaml#/DATVDemodSettings"
    DABDemodSettings:
      $ref: "/doc/swagger/include/DABDemod.yaml#/DABDemodSettings"
    DOA2Settings:
      $ref: "/doc/swagger/include/DOA2.yaml#/DOA2Settings"
    DSDDemodSettings:
      $ref: "/doc/swagger/include/DSDDemod.yaml#/DSDDemodSettings"
    FileSinkSettings:
      $ref: "/doc/swagger/include/FileSink.yaml#/FileSinkSettings"
    FileSourceSettings:
      $ref: "/doc/swagger/include/FileSource.yaml#/FileSourceSettings"
    FreeDVDemodSettings:
      $ref: "/doc/swagger/include/FreeDVDemod.yaml#/FreeDVDemodSettings"
    FreeDVModSettings:
      $ref: "/doc/swagger/include/FreeDVMod.yaml#/FreeDVModSettings"
    FreqTrackerSettings:
      $ref: "/doc/swagger/include/FreqTracker.yaml#/FreqTrackerSettings"
    FT8DemodSettings:
      $ref: "/doc/swagger/include/FT8Demod.yaml#/FT8DemodSettings"
    RTTYDemodSettings:
      $ref: "/doc/swagger/include/RTTYDemod.yaml#/RTTYDemodSettings"
    HeatMapSettings:
      $ref: "/doc/swagger/include/HeatMap.yaml#/HeatMapSettings"
    InterferometerSettings:
      $ref: "/doc/swagger/include/Interferometer.yaml#/InterferometerSettings"
    IEEE_802_15_4_ModSettings:
      $ref: "/doc/swagger/include/IEEE_802_15_4_Mod.yaml#/IEEE_802_15_4_ModSettings"
    M17DemodSettings:
      $ref: "/doc/swagger/include/M17Demod.yaml#/M17DemodSettings"
    M17ModSettings:
      $ref: "/doc/swagger/include/M17Mod.yaml#/M17ModSettings"
    NavtexDemodSettings:
      $ref: "/doc/swagger/include/NavtexDemod.yaml#/NavtexDemodSettings"
    NFMDemodSettings:
      $ref: "/doc/swagger/include/NFMDemod.yaml#/NFMDemodSettings"
    NFMModSettings:
      $ref: "/doc/swagger/include/NFMMod.yaml#/NFMModSettings"
    NoiseFigureSettings:
      $ref: "/doc/swagger/include/NoiseFigure.yaml#/NoiseFigureSettings"
    LocalSinkSettings:
      $ref: "/doc/swagger/include/LocalSink.yaml#/LocalSinkSettings"
    LocalSourceSettings:
      $ref: "/doc/swagger/include/LocalSource.yaml#/LocalSourceSettings"
    PacketDemodSettings:
      $ref: "/doc/swagger/include/PacketDemod.yaml#/PacketDemodSettings"
    PacketModSettings:
      $ref: "/doc/swagger/include/PacketMod.yaml#/PacketModSettings"
    PagerDemodSettings:
      $ref: "/doc/swagger/include/PagerDemod.yaml#/PagerDemodSettings"
    RadioAstronomySettings:
      $ref: "/doc/swagger/include/RadioAstronomy.yaml#/RadioAstronomySettings"
    RadioClockSettings:
      $ref: "/doc/swagger/include/RadioClock.yaml#/RadioClockSettings"
    RadiosondeDemodSettings:
      $ref: "/doc/swagger/include/RadiosondeDemod.yaml#/RadiosondeDemodSettings"
    RemoteSinkSettings:
      $ref: "/doc/swagger/include/RemoteSink.yaml#/RemoteSinkSettings"
    RemoteSourceSettings:
      $ref: "/doc/swagger/include/RemoteSource.yaml#/RemoteSourceSettings"
    RemoteTCPSinkSettings:
      $ref: "/doc/swagger/include/RemoteTCPSink.yaml#/RemoteTCPSinkSettings"
    SigMFFileSinkSettings:
      $ref: "/doc/swagger/include/SigMFFileSink.yaml#/SigMFFileSinkSettings"
    SSBModSettings:
      $ref: "/doc/swagger/include/SSBMod.yaml#/SSBModSettings"
    SSBDemodSettings:
      $ref: "/doc/swagger/include/SSBDemod.yaml#/SSBDemodSettings"
    UDPSourceSettings:
      $ref: "/doc/swagger/include/UDPSource.yaml#/UDPSourceSettings"
    UDPSinkSettings:
      $ref: "/doc/swagger/include/UDPSink.yaml#/UDPSinkSettings"
    # VORDemodMCSettings:
    #   $ref: "/doc/swagger/include/VORDemodMC.yaml#/VORDemodMCSettings"
    VORDemodSettings:
      $ref: "/doc/swagger/include/VORDemod.yaml#/VORDemodSettings"
    WFMDemodSettings:
      $ref: "/doc/swagger/include/WFMDemod.yaml#/WFMDemodSettings"
    WFMModSettings:
      $ref: "/doc/swagger/include/WFMMod.yaml#/WFMModSettings"
